version: '3'

services:
  my_python_app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python SuperMongo2.py
    depends_on:
      - cassandra
      - neo4j

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password  # Configura las credenciales según sea necesario

