version: '3'

services:
  my_python_app:
    build:
      context: .
      dockerfile: Dockerfile.dockerfile
    command: >
      bash -c "python SuperMongo2.py && python SuperCassandra.py && python updataneo.py"
    depends_on:
      - cassandra
      - neo4j
      - mongo  # Agregado servicio de MongoDB

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/12345678  # Configura las credenciales según sea necesario

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
